### ISSUE TITLE
BXR file without 3BResults is not recognized as BXR

### ISSUE THREAD

**Issue by OttAle** [Helveg/bwpy#11]
When I open bxr files without a 3BResult group in them none of the bxr functions work, like get_channel_group

**Comment by Helveg** [comment]
This is because I decided not to use the extension to detect file type  but rather the HDF5 content and `3BResults` is the determinant for the `BXR` type. Since the HDF5 guide explicitly states that the descriptions should start with either `BXR` or `BRW` I think I'll start using the description to determine the type.
